#!/bin/sh
# make sure at least one param passed
if [ ! "$#" -ge 1 ]; then
  echo "Incorrect number of arguments."
  echo "Usage: clean_list list"
  exit 1
fi

for arg
  do
    for temp in `echo $arg | sed -e 's/^:/.:/' -e 's/::/:.:/' -e 's/:$/:./' -e 's/:/ /g'`
      do
        case $list in
    
        "")
          list="$temp"
        ;;

        $temp|$temp:*|*:$temp:*|*:$temp)
          continue
        ;;

        *)
          list="$list:$temp"
        ;;
        
        esac
      done
  done
echo $list
