import blockContent from './blockContent'
import blockContentImage from './objects/blockContentImage'
import bodyText from './objects/bodyText'
import breadcrumbs from './objects/breadcrumbs'
import contactForm from './objects/contactForm'
import crumb from './objects/crumb'
import footerLink from './objects/footerLink'
import hero from './objects/hero'
import htmlBlock from './objects/htmlBlock'
import imageRow from './objects/imageRow'
import imageBlock from './objects/imageBlock'
import imageRowVideo from './objects/imageRowVideo'
import logoCycler from './objects/logoCycler'
import page from './page'
import siteSettings from './siteSettings'
import titleText from './objects/titleText'
import videoBlock from './objects/videoBlock'

export const schemaTypes = [blockContent, blockContentImage, bodyText, breadcrumbs, contactForm, crumb, footerLink, hero, htmlBlock, imageBlock, imageRow, imageRowVideo, logoCycler, page, siteSettings, titleText, videoBlock]
